"""Client for Eloverblik (Energinet DataHub)'s Customer API — a Danish user's
own smart-meter consumption.

Endpoints and request/response shapes follow Energinet's "Customer and Third
Party API for DataHub (Eloverblik) — Technical Description" (doc 19/11830-1,
rev. 1.7.8/2.7.6, 2025-03-27). A refresh token is generated by the user on
eloverblik.dk (Data access -> Data access via API) and never expires on its
own; it is exchanged here for a 24-hour access token.
"""
import json
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timedelta, timezone

API_BASE = "https://api.eloverblik.dk/customerapi"


class EloverblikError(Exception):
    pass


def _request(path, refresh_token=None, access_token=None, method="GET", body=None, timeout=15):
    url = f"{API_BASE}{path}"
    req = urllib.request.Request(url, method=method)
    token = access_token or refresh_token
    req.add_header("Authorization", f"Bearer {token}")
    data = None
    if body is not None:
        req.add_header("Content-Type", "application/json")
        req.add_header("Accept", "application/json")
        data = json.dumps(body).encode()
    try:
        with urllib.request.urlopen(req, data=data, timeout=timeout) as resp:
            raw = resp.read()
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", "replace")[:300]
        raise EloverblikError(f"HTTP {exc.code}: {detail}") from exc
    except (urllib.error.URLError, OSError) as exc:
        raise EloverblikError(f"request failed: {exc}") from exc
    try:
        return json.loads(raw) if raw else {}
    except ValueError as exc:
        raise EloverblikError(f"bad JSON: {exc}") from exc


def get_access_token(refresh_token, timeout=15):
    """Exchange the long-lived refresh token for a 24h data access token."""
    body = _request("/api/token", refresh_token=refresh_token, timeout=timeout)
    token = body.get("result")
    if not token:
        raise EloverblikError(f"no access token in response: {body}")
    return token


def list_metering_points(access_token, include_all=False, timeout=15):
    """Metering points linked to the user (or all registered to them, if
    include_all), as the raw records the API returns — field names are not
    pinned down here so a UI can show whatever address/type fields exist."""
    qs = urllib.parse.urlencode({"includeAll": "true" if include_all else "false"})
    body = _request(
        f"/api/meteringpoints/meteringpoints?{qs}", access_token=access_token, timeout=timeout
    )
    result = body.get("result")
    if isinstance(result, dict):
        result = result.get("meteringPoints") or result.get("MeteringPoints") or []
    return result if isinstance(result, list) else []


def get_hourly_consumption(access_token, metering_point_id, date_from, date_to, timeout=30):
    """Hourly consumption in kWh for one metering point over [date_from, date_to).

    date_from/date_to are date() objects or "YYYY-MM-DD" strings. Returns a
    list of {"time_utc": ISO str (hour start), "kwh": float, "quality": str},
    ascending by time. Eloverblik commonly lags 1-3 days behind for measured
    (non-estimated) readings.
    """
    d_from = date_from if isinstance(date_from, str) else date_from.strftime("%Y-%m-%d")
    d_to = date_to if isinstance(date_to, str) else date_to.strftime("%Y-%m-%d")
    # Energinet's own technical description (doc 19/11830-1) documents this
    # body as a flat {"meteringPointIds": [...]} array. The live API rejects
    # that with "#20013: No meteringpoints in request conforms to valid
    # meteringpoint format" — the docs are wrong here. Every working client
    # (pyeloverblik, nim_eloverblik_api) instead sends this nested shape,
    # which is what the API actually expects.
    body = _request(
        f"/api/meterdata/gettimeseries/{d_from}/{d_to}/Hour",
        access_token=access_token,
        method="POST",
        body={"meteringPoints": {"meteringPoint": [metering_point_id]}},
        timeout=timeout,
    )
    return _parse_time_series(body)


def _parse_time_series(body):
    result = body.get("result")
    if not isinstance(result, list) or not result:
        return []
    document = result[0].get("MyEnergyData_MarketDocument") or {}
    series_list = document.get("TimeSeries") or []
    out = []
    for series in series_list:
        for period in series.get("Period") or []:
            start = _parse_iso(((period.get("timeInterval") or {}).get("start")))
            if start is None:
                continue
            points = period.get("Point") or []
            for point in points:
                try:
                    position = int(point.get("position"))
                    quantity = float(point.get("out_Quantity.quantity"))
                except (TypeError, ValueError):
                    continue
                hour_start = start + timedelta(hours=position - 1)
                out.append(
                    {
                        "time_utc": hour_start.isoformat(),
                        "kwh": quantity,
                        "quality": point.get("out_Quantity.quality"),
                    }
                )
    out.sort(key=lambda r: r["time_utc"])
    return out


def _parse_iso(value):
    if not value:
        return None
    try:
        return datetime.fromisoformat(value.replace("Z", "+00:00")).astimezone(timezone.utc)
    except ValueError:
        return None
